GET http://localhost:3000/users/

### check 

post http://localhost:3000/users/check 
Content-Type: application/json

{"currency": "usd", "amount": 2000}

### solve

post http://localhost:3000/users/check 
Content-Type: application/json

{"currency": "usd", "amount": 2000}
 